### ISSUE TITLE
Type Error : missing 1 positional argument: 'Training task'

### ISSUE THREAD

**Issue by parasmech** [idthanm/env_build#82]
Hello Mr. Yang.

Thanks for this repository. 

When I am running the environment in Colab using
env = gym.make('CrossroadEnd2end-v0').

I am geting this Typeerror::
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-45-d26cffa5af4d> in <module>()
----> 1 env = gym.make('CrossroadEnd2end-v0')
      2 

2 frames
/usr/local/lib/python3.7/dist-packages/gym/envs/registration.py in make(self, **kwargs)
     58         else:
     59             cls = load(self.entry_point)
---> 60             env = cls(**_kwargs)
     61 
     62         # Make the environment aware of which spec it came from.

TypeError: __init__() missing 1 required positional argument: 'training_task'

Please help me to solve this.  

Regards

**Comment by parasmech** [comment]
Hello Mr Yang

I am getting this error now

python3 ./gym_test.py 
2021-12-17 09:55:22.626259: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/ros/melodic/lib
2021-12-17 09:55:22.626376: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
/home/paras/.local/lib/python3.7/site-packages/ale_py/roms/utils.py:90: DeprecationWarning: SelectableGroups dict interface is deprecated. Use select.
  for external in metadata.entry_points().get(self.group, []):
Traceback (most recent call last):
  File "./gym_test.py", line 1, in <module>
    import gym
  File "/home/paras/.local/lib/python3.7/site-packages/gym/__init__.py", line 13, in <module>
    from gym.envs import make, spec, register
  File "/home/paras/.local/lib/python3.7/site-packages/gym/envs/__init__.py", line 20, in <module>
    reward_threshold=195.0,
  File "/home/paras/.local/lib/python3.7/site-packages/gym/envs/registration.py", line 233, in register
    return registry.register(id, **kwargs)
  File "/home/paras/.local/lib/python3.7/site-packages/gym/envs/registration.py", line 219, in register
    self.env_specs[id] = EnvSpec(id, **kwargs)
  File "/home/paras/.local/lib/python3.7/site-packages/gym/envs/registration.py", line 71, in __init__
    id, env_id_re.pattern
gym.error.Error: Attempted to register malformed environment ID: CartPole-v0. (Currently all IDs must be of the form CrossroadEnd2end-v0.)

Is there anything to change in regisration.py file ?

Thanks for the help

Regards
